### ISSUE TITLE
Missing 'bond type' attribute

### ISSUE THREAD

**Issue by ChenglongWang** [materialsvirtuallab/matgl#214]
### Discussed in https://github.com/materialsvirtuallab/matgl/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **ChenglongWang** January  8, 2024</sup>
Dear matgl team. Thanks for your hard working on this tool.

We are currently in the process of utilizing matgl with our in-house data, aligning our efforts with the remarkable insights detailed in the MEGNet paper (DOI: 10.1021/acs.chemmater.9b01294). However, during our experiment, we encountered a discrepancy concerning the presence of many attributes such as 'bond type' attribute within the edge attributes of the molecular graph.

Considering that the MEGNet model was initially implemented in TensorFlow, we kindly request your assistance in clarifying whether the Pytorch implementation considered the "bond type" attribute in case we missed it. If it is not included, we would greatly appreciate guidance on any available method to retrieve the bond type attributes within the current PyTorch implementation.

Any guidance or support you can provide regarding this matter would be immensely appreciated.
Thanks.</div>

**Comment by kenko911** [comment]
Hi @ChenglongWang, thanks for your questions. In the current MEGNet implementation, we are only supporting bond distance as edge attributes since we observe that the actual performance of MEGNet models with only geometrical information is comparable to models with all bond types (see MEGNet paper). Including bond type requires certain modifications in MEGNetDataset and MEGNet model class.
